### ISSUE TITLE
Bind hb-subset

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/uharfbuzz#102]
It would be nice to have bindings for the subset library, after its API is stabilized (i.e. after HarfBuzz 3.0.0).

**Comment by madig** [comment]
If one were to hypothetically look into this, where would they start? Which functions and associated types, etc. need to be exposed?

**Comment by behdad** [comment]
> If one were to hypothetically look into this, where would they start? Which functions and associated types, etc. need to be exposed?

https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset.h

**Comment by behdad** [comment]
> If one were to hypothetically look into this, where would they start? Which functions and associated types, etc. need to be exposed?

The main entry point is `hb_subset_or_fail`:
https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset.h#L195
