### ISSUE TITLE
Obtaining `hb_font_extents_t`?

### ISSUE THREAD

**Issue by takaakifuji** [harfbuzz/uharfbuzz#106]
Currently the binding to `hb_font_get_extents_for_direction()` does not exist.

I think it's useful to implement `hb-view` ish utilities in Python. What are your thoughts?

**Comment by anthrotype** [comment]
yes why not, would you like to work on a PR?

**Comment by HinTak** [comment]
Already done in a different way, a few years ago: https://github.com/HinTak/harfbuzz-python-demos

**Comment by takaakifuji** [comment]
Thanks, I'll make a PR after having a look at @HinTak's implementation.
