### ISSUE TITLE
access to hb_font_set_ppem and hb_font_set_ptem

### ISSUE THREAD

**Issue by smason** [harfbuzz/uharfbuzz#114]
Just been looking through `uharfbuzz` and the [fonts and faces](https://harfbuzz.github.io/fonts-and-faces.html) section of the Harfbuzz docs which suggests setting `hb_font_set_ppem` and `hb_font_set_ptem`.

I don't see any way of accessing these attributes but wondered if I was missing something obvious.

It looks like a trivial fix, if the `scale` properties are anything to go by, but wanted to ask before making a pull request.

**Comment by khaledhosny** [comment]
PR is welcome, I think they were not supported because they are don’t make any difference in practice most of the time as HarfBuzz uses them only sparsely.

**Comment by behdad** [comment]
> PR is welcome, I think they were not supported because they are don’t make any difference in practice most of the time as HarfBuzz uses them only sparsely.

Correct.

**Comment by smason** [comment]
> PR is welcome

done, mostly because of the incongruity from upstream docs

> I think they were not supported because they are don’t make any difference in practice most of the time as HarfBuzz uses them only sparsely.

I'm assuming "they [..] don't make any difference in practice" because most fonts don't support them, rather than HarfBuzz not propagating these settings appropriately?

**Comment by khaledhosny** [comment]
Most fonts don’t have use for them.
