### ISSUE TITLE
`Blob.from_file_path` does not bail on error

### ISSUE THREAD

**Issue by madig** [harfbuzz/uharfbuzz#116]
The following snippet will not raise an error:

```py
import uharfbuzz as hb
hb.Blob.from_file_path("asdasgdjh")
```

It should probably use https://harfbuzz.github.io/harfbuzz-hb-blob.html#hb-blob-create-from-file-or-fail under the hood?

**Comment by anthrotype** [comment]
Yes it should

**Comment by khaledhosny** [comment]
The C API  does not bail on error by design, I think there is an issue for this on HarfBuzz bug tracker and ways to detect failure.

**Comment by behdad** [comment]
In C the way is to check for equality to the empty blob. But in Python I think using the create_from_file_or_fail and throwing exception is fine...

**Comment by khaledhosny** [comment]
I forgot about the or_fail variant.
