### ISSUE TITLE
New Release for Repacking Bugfix

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/uharfbuzz#127]
It would be good to get out a new release that contains the harfbuzz change https://github.com/harfbuzz/harfbuzz/commit/9c2518988dcdafb8388f8f1f5e76db6e08ef6a0e

This fixes an issue in fonttool's use of the repacker: https://github.com/fonttools/fonttools/issues/2691

**Comment by anthrotype** [comment]
We usually wait for upstream harfbuzz to cut a release before updating our submodule to the respective tag. I could temporarily point it to latest hb master and cut a pre-release while upstream makes a new release that includes the change.

**Comment by anthrotype** [comment]
I just cut a pre-release v0.27.0b1 that includes the upstream repacker fix: https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.27.1b1

One can install it with `pip install --upgrade --pre uharfbuzz` if they like.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.28.0
