### ISSUE TITLE
get_glyph_shape() should be a method of Font rather than DrawFuncs

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#133]
IMO, `get_glyph_shape()` should be a method of `Font` rather than `DrawFuncs`. The first argument to `hb_font_get_glyph_shape()` is a `hb_font` after all.

I find it a little odd we ask the `DrawFuncs` to get the glyph shape. To me, the question is: "hey font, please give me the glyph shape, using these DrawFuncs as tools."

    font.get_glyph_shape(gid, draw_funcs)

`draw_glyph_with_pen()` is also a `Font` method.

Is it worth changing, with a deprecation warning for the existing `DrawFuncs` method?

**Comment by khaledhosny** [comment]
Makes sense. We probably should take a step back and re-design this API as it was designed before the final HarfBuzz API was settled on, and may be make a breaking change this this time since it is getting really convoluted.

**Comment by justvanrossum** [comment]
Also, I think `get_glyph_shape()` should have a `draw_data` argument. But see https://github.com/harfbuzz/harfbuzz/discussions/3765, I'm not sure I understand that argument.

**Comment by khaledhosny** [comment]
Yes, that is the main reason I think the Python API needs to be redesigned. When it was written there was no `draw_data`.

**Comment by justvanrossum** [comment]
It's already pretty close to being a good parallel to the C API, I don't think that it needs a big redesign. We should just make `get_glyph_shape` a method of `Font`, and add the `draw_data` argument.

`draw_data` is better than `user_data` for FontGoggles *and* `draw_glyph_with_pen`, as in both cases we can use a singleton `DrawFuncs` instance instead of instantiating a new one for every single call.

**Comment by khaledhosny** [comment]
I think the complication would be adapting the convoluted (but probably necessary) way in which pure Python callaback functions are wrapped.

**Comment by justvanrossum** [comment]
Right, I see. Also, the pure Python callbacks are a much simplified version of the C callbacks. Yeah, more thinking and designing would be good.
