### ISSUE TITLE
New release needed to grab repacking bugfix from harfbuzz

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/uharfbuzz#136]
https://github.com/harfbuzz/harfbuzz/commit/99f4668e1969a0a688044433803b3e7797391688 fixes a bug in the repacker that can result in incorrect packing via hb_repack in some rare cases.

**Comment by anthrotype** [comment]
we usually update the harfbuzz git sumbodule to the latest tagged release, when that's available we can update and make a new uharfbuzz release. We can update temporarily to an unreleased harfbuzz commit but before next uharfbuzz stable release ideally we'd have a stable harbuzz release too

**Comment by garretrieger** [comment]
New release will be coming for harfbuzz including this commit: https://github.com/harfbuzz/harfbuzz/issues/3836

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.31.0

**Comment by anthrotype** [comment]
Thanks!
