### ISSUE TITLE
New release needed for harfbuzz 5.3.1

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/uharfbuzz#138]
https://github.com/harfbuzz/uharfbuzz/commit/bf4105e6ebcb862e34a45676ca17a67bc65d9314 updated to harfbuzz 5.3.1. Can we get a new release that includes this commit?

**Comment by anthrotype** [comment]
https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.32.0
