### ISSUE TITLE
Build harfbuzz with experimental features by default?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/uharfbuzz#140]
A suggestion.

**Comment by behdad** [comment]
The rationale being that uharfbuzz is mostly used by cutting-edge tools like FontGoggles and Crowbar, and those can use demoing the experimental features in harfbuzz most.

**Comment by khaledhosny** [comment]
I though we do this already. Probably we stopped doing this when hb-draw became stable, fine by me especially for features that does not affect the Python API.

**Comment by behdad** [comment]
I think you're right.

**Comment by anthrotype** [comment]
No objections from me

**Comment by khaledhosny** [comment]
We still build with it indeed:
https://github.com/harfbuzz/uharfbuzz/blob/b7a809ddedd138622ccb2d9c573a64528a16eb67/setup.py#L16

**Comment by khaledhosny** [comment]
Or may be you meant some other define?

**Comment by behdad** [comment]
That's all I meant. All good. Thanks.
