### ISSUE TITLE
can't install uharfbuzz due to cython new version 3

### ISSUE THREAD

**Issue by cyrilus** [harfbuzz/uharfbuzz#164]
pip install can't work due to cython 3.0 release
I have try to correct this in my PR
https://github.com/harfbuzz/uharfbuzz/pull/163

**Comment by anthrotype** [comment]
maybe this can help: 
https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html?highlight=noexcept

**Comment by anthrotype** [comment]
If I set the legacy_implicit_noexcept=True cython compiler directive in setup.py, then the build completes but we get a bunch of warnings about 

warning: src/uharfbuzz/_harfbuzz.pyx:60:40: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

so it must be related to this change:
https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html?highlight=noexcept#exception-values-and-noexcept

**Comment by anthrotype** [comment]
adding 'noexcept' keyword to all the function declarations where we get those warnings also fixes the build, but I am not 100% sure it is always the correct thing to do...
