### ISSUE TITLE
Crash when repacking fonts with latest binary wheels (v0.37.1, v0.37.1.post1)

### ISSUE THREAD

**Issue by Hoolean** [harfbuzz/uharfbuzz#168]
Hello!

A segfault occurs when building fonts on Windows (amd64) with the latest uharfbuzz binary wheels ([v0.37.1](https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.37.1), [v0.37.1.post1](https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.37.1.post1)) on pypi. More specifically, it occurs when saving TTFs with HarfBuzz binary repacking enabled.

## Reproducing

1. Clone googlefonts/roboto-classic@58302217
2. Create a venv and install fontmake and uharfbuzz==0.37.1 (Windows amd64 binary wheel)
3. Run `fontmake -m .\sources\Roboto.designspace -o variable`
4. fontmake segfaults, the output log is truncated, and no TTF is created

## Additional Details

In addition to testing with the binary wheel deployed on pypi, we also tested locally, which gave strange results:

| uharfbuzz version | Windows 10 | Windows 11 |
|-|-|-|
| v0.37.0 amd64 pypi wheel | ✔️ | ✔️ |
| v0.37.1 amd64 pypi wheel | 💥 | 💥 |
| v0.37.1.post1 amd64 pypi wheel | 💥 | 💥 |
| v0.37.1.post1 built locally with VS Community 2022 v17.6.4 | ✔️ | ❔ |
| v0.37.1.post1 built locally with VS Community (or Build Tools?) 2022 v17.5.5 | ❔ | 💥 |
| v0.37.1.post1 with HarfBuzz 7 retrofitted, built locally with VS Community (or Build Tools?) 2022 v17.5.5 | ❔ | ✔️ |
| v0.37.1.post1 built locally with VS Community 2022 v17.6.5 | ❔ | ✔️ |

**Comment by behdad** [comment]
@garretrieger

**Comment by behdad** [comment]
Seems to work for me on Linux.

**Comment by Hoolean** [comment]
Whoops, yes, I forgot to add that we tested one of the Linux pypi wheels for v0.37.1.post1 in WSL2 and it worked fine :+1:

**Comment by Hoolean** [comment]
From a hunt with @anthrotype and @madig, we suspect that you can reproduce reliably with a uharfbuzz based on HarfBuzz 8 and an unlucky Windows build environment (including the one used in this project's CI runner)

**Comment by behdad** [comment]
Is there the HB build log somewhere in there I can inspect for any compiler warnings?

**Comment by Hoolean** [comment]
Both @madig and I are on the latest (non-reproducing) VS version now so our best bet might be to increase the verbosity of the CI runner's build (which is [a little sparse](https://github.com/harfbuzz/uharfbuzz/actions/runs/5608792128/job/15195095850#step:5:1299) right now 😁)

**Comment by Hoolean** [comment]
Hello again @behdad, we persuaded the CI to show us [the HB build log](https://github.com/harfbuzz/uharfbuzz/actions/runs/5655714445/job/15321351759?pr=169#step:5:5206) :) Does this offer us any clues?

**Comment by anthrotype** [comment]
have you tried to use the https://docs.python.org/3/library/faulthandler.html to see the python traceback right before the segfault?

**Comment by Hoolean** [comment]
> have you tried to use the https://docs.python.org/3/library/faulthandler.html to see the python traceback right before the segfault?

I've not tried this yet but I suspect it will give us a Python-side strack trace pointing at `hb.repack()`; I just built with AddressSanitizer on #170 to get a C++-side stack trace, but with the inclusion of this I can no longer reproduce (!).

I am at a bit of a loss here...

@behdad @anthrotype Any ideas?

**Comment by anthrotype** [comment]
Heisenbug! 🤯

**Comment by anthrotype** [comment]
Usually people recommend running the GNU Debugger (gdb) to debug segfaults that happen inside a Python extension module but AFAIU it doesn't seem to be possible/easily achievable on Windows. I think gdb itself has to be built from source with python support. MinGW-w64 has gdb but it uses gcc as compiler, not MSVC, and the uharfbuzz windows wheels are compiled with the native MSVC compiler, so I don't think you can use that gdb to debug them.

Visual Studio itself (not vscode but the big brother) has a debugger that supports both python and c++:

https://learn.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022

but I guess one needs to create a whole VS project for uharfbuzz and I have no idea how to do that.

I also found a vscode extension that claims to allow debugging mixed Python and C++ code. Their example uses ctypes though: https://github.com/benibenj/vscode-pythonCpp
I cannot test any of this because I don't have access to a windows machine right now unfortunately.

**Comment by anthrotype** [comment]
and we don't actually know if the segfault is happening in the harfbuzz library or in our own cython-generated glue code. If we could dump the blob of data that hb_repack is receiving and found a way to pass it to without using neither python nor cython (e.g. a little C utility that reads the blob from a file and calls hb_repack?) and we are able to repro the segfault then we'd be certain that it's happening in harfbuzz and not in cython wrapper...

**Comment by anthrotype** [comment]
I believe they did manage to reproduce with uharfbuzz built locally, see the table at the beginning, which repros the crash on Windows 11 at least:

> v0.37.1.post1 built locally with VS Community (or Build Tools?) 2022 v17.5.5

@Hoolean @madig is that correct?

**Comment by madig** [comment]
He had both installed and we didn't know how to differentiate which one was used.

**Comment by HinTak** [comment]
And you can watch how harfbuzz proper is talking to the C runtime (in this case, wine's), too.

**Comment by behdad** [comment]
> Here is a suggestion that may be a bit beyond some of you: does it crash under wine?

We were just discussing that. Might require a wine Python though, and building uharfbuzz module under wine. A bit of work and I'm not sure how to do quite.

**Comment by HinTak** [comment]
Python installs and runs under wine just fine. It has been a while since I tried it though. The other suggestion is valgrind on Windows. That might be easier?

**Comment by HinTak** [comment]
Actually most of wine itself are windows PE these days (and cross-compiled), with very few "native" host bits. (It happened in wine 7 or wine 8). You shouldn't need to rebuild anything - that's the whole point: in case rebuilding causes the bug to disappear.

**Comment by anthrotype** [comment]
> valgrind on Windows

I didn't know one could use valgrind on windows to debug a DLL that was compiled with Visual Studio (not with mingw gcc).
Checking if it also segfaults under wine is definitely worth a try.

**Comment by HinTak** [comment]
I don't know if valgrind works well on Windows - just we are talking about "debugging release binaries without special re-compilation" techniques. Wine is definitely a good direction if some of you can find your way around it. It has a built-in debugger with a gdb-like interface, called "winedebug".

**Comment by HinTak** [comment]
In this case, I think mostly you want to look up on "relay" logging. That's the logging/tracing mode in wine for looking at inter-dll communications.

**Comment by behdad** [comment]
I'm trying the wine route, but failing for my mingw64 python to load the extension module in the uharfbuzz wheel. :(

**Comment by HinTak** [comment]
You should be able to install the normal win32 python with something like "wine msiexec the_python_installer.msi" if it is in msi form, otherwise just do "wine installer.exe". Afterwards, do "wine cmd" to get your usual command prompt to run python as you do in Windows.

**Comment by behdad** [comment]
I have python running from Fedora's compiled mingw64 repos. It just doesn't load the uharfbuzz wheel.

**Comment by HinTak** [comment]
Is that win32 python or win64 python? I think wine on fedora will do 64 to 32 for you but not vice versa. If you want to force 32-bit mode in wine, you do "WINEARCH=win32 wine ...".

**Comment by behdad** [comment]
Trying all the 64bit.

**Comment by HinTak** [comment]
Wine is quite okay just installing the official windows python installer the normal way. I don't remember why, but I have definitely done it in the past.

**Comment by anthrotype** [comment]
I don't think the uharfbuzz binary wheels will work on the mingw64-compiled python, you should try to download the official installer from python.org, the 64-bit one which I think Harry and Nikolaus are using.

**Comment by behdad** [comment]
> I don't think the uharfbuzz binary wheels will work on the mingw64-compiled python, you should try to download the official installer from python.org, the 64-bit one which I think Harry and Nikolaus are using.

Yeah I've finally managed to reproduce it on wine64 and official python 3.11... I even enabled debug info, but looks like winedbg doesn't understand the .pdb debuginfo file that MSVC generates. So all I've got is the following stacktrace:
```
Backtrace:
=>0 0x00000002233353 in _harfbuzz.cp311-win_amd64.pyd (+0xc3353) (0x0000000020e370)
  1 0x00000002176f96 in _harfbuzz.cp311-win_amd64.pyd (+0x6f96) (0x0000000020e4a0)
  2 0x000000021763b6 in _harfbuzz.cp311-win_amd64.pyd (+0x63b6) (0x0000000020e770)
  3 0x000000021fe7a1 in _harfbuzz.cp311-win_amd64.pyd (+0x8e7a1) (0x0000000020e900)
  4 0x000000021feb47 in _harfbuzz.cp311-win_amd64.pyd (+0x8eb47) (0x0000000020ea60)
  5 0x000000023009da in _harfbuzz.cp311-win_amd64.pyd (+0x1909da) (0x00000019d8bd20)
  6 0x000000023000be in _harfbuzz.cp311-win_amd64.pyd (+0x1900be) (0x00000000000003)
```
I tried another tool called `pdb-addr2line` to decode the addresses. It seems to give locations in the ballpark, but not quite meaningful...

**Comment by behdad** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> I tried another tool called `pdb-addr2line` to decode the addresses. It seems to give locations in the ballpark, but not quite meaningful...

Here's the stacktrace I get from pdb-addr2line. As I said, the functions are in the ballpark, but the topmost three don't make sense.
```
0x000000000014ecb3
hb_array_t<hb_serialize_context_t::object_t::link_t>::__forward__(unsigned int)
D:\a\uharfbuzz\uharfbuzz\harfbuzz\src\hb-array.hh:103

0x000000000000b016
hb_bit_set_invertible_t::iter_t::{ctor}(hb_bit_set_invertible_t const&, bool)
D:\a\uharfbuzz\uharfbuzz\harfbuzz\src\hb-bit-set-invertible.hh:350

0x000000000000a436
hb_bit_set_t::in_error() const
D:\a\uharfbuzz\uharfbuzz\harfbuzz\src\hb-bit-set.hh:86

0x00000000000d9161
hb_resolve_graph_overflows(unsigned int, unsigned int, bool, graph::graph_t&)
D:\a\uharfbuzz\uharfbuzz\harfbuzz\src\hb-repacker.hh:317

0x00000000000d9517
hb_resolve_overflows(hb_vector_t<hb_object_t const *,0> const&, unsigned int, unsigned int, bool)
D:\a\uharfbuzz\uharfbuzz\harfbuzz\src\hb-repacker.hh:404

0x00000000003c4c0a
__pyx_pf_9uharfbuzz_9_harfbuzz_16repack_with_tag(_object*, _object*, _object*, _object*)
D:\a\uharfbuzz\uharfbuzz\src\uharfbuzz\_harfbuzz.cpp:29889

0x00000000003c42ee
__pyx_pw_9uharfbuzz_9_harfbuzz_17repack_with_tag(_object*, _object* const*, long long, _object*)
D:\a\uharfbuzz\uharfbuzz\src\uharfbuzz\_harfbuzz.cpp:29508
```

**Comment by anthrotype** [comment]
Are we 100% sure the segfault happens inside harfbuzz and not in the cython code that prepares the objects or receives the blob for hb_repack? 
If not, how easy/hard would it be to dump the roboto-classic's blob of data that hb_repack is receiving, just before we segfault, and write a little c++ program that links to libharfbuzz and reads this blob from a file and calls hb_repack?
If we can still repro the segfault, we'd be certain that it's happening inside harfbuzz and not in the cython wrapper.

**Comment by HinTak** [comment]
Good you are making progresses. Wine's relay log can look at inter-dll communications...

**Comment by behdad** [comment]
> Are we 100% sure the segfault happens inside harfbuzz

Given the rough stacktrace, I'm sure it's crashing inside harfbuzz repacker.

**Comment by behdad** [comment]
And only when compiled with optimizations enabled.

**Comment by behdad** [comment]
> Here's the stacktrace I get from pdb-addr2line. As I said, the functions are in the ballpark, but the topmost three don't make sense.

Chad debugged it on Windows, and he gets the same backtrace. So I think it's safe to say that pdb-addr2line is doing the right thing. It's just that the .pdb is confused?

**Comment by behdad** [comment]
> > Here's the stacktrace I get from pdb-addr2line. As I said, the functions are in the ballpark, but the topmost three don't make sense.
> 
> Chad debugged it on Windows, and he gets the same backtrace. So I think it's safe to say that pdb-addr2line is doing the right thing. It's just that the .pdb is confused?

Or not. I'm studying his trace now.

**Comment by dfrg** [comment]
Slightly different call stack:
```
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_array_t<hb_serialize_context_t::object_t::link_t>::__forward__(unsigned int) Line 103	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_serialize_context_t::object_t::link_t &>::operator+=(unsigned int) Line 92	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_serialize_context_t::object_t::link_t &>::operator+(unsigned int) Line 100	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_fallback_mixin_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_serialize_context_t::object_t::link_t &>::__end__() Line 221	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_serialize_context_t::object_t::link_t &>::_end() Line 79	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_concat_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_array_t<hb_serialize_context_t::object_t::link_t>>::__end__() Line 651	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_t<hb_concat_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_array_t<hb_serialize_context_t::object_t::link_t>>,hb_serialize_context_t::object_t::link_t &>::_end() Line 79	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_iter_t<hb_concat_iter_t<hb_array_t<hb_serialize_context_t::object_t::link_t>,hb_array_t<hb_serialize_context_t::object_t::link_t>>,hb_serialize_context_t::object_t::link_t &>::end() Line 80	C++
>	_harfbuzz.cp311-win_amd64.pyd!graph::graph_t::remap_obj_indices<hb_bit_set_invertible_t::iter_t,0>(const hb_map_t & id_map, hb_bit_set_invertible_t::iter_t subgraph, bool) Line 1326	C++
 	_harfbuzz.cp311-win_amd64.pyd!graph::graph_t::isolate_subgraph(hb_set_t & roots) Line 735	C++
 	_harfbuzz.cp311-win_amd64.pyd!graph::graph_t::assign_spaces() Line 649	C++
 	_harfbuzz.cp311-win_amd64.pyd!hb_resolve_graph_overflows(unsigned int table_tag, unsigned int recalculate_extensions, bool sorted_graph, graph::graph_t &) Line 317	C++
 	[Inline Frame] _harfbuzz.cp311-win_amd64.pyd!hb_resolve_overflows(const hb_vector_t<hb_object_t const *,0> &) Line 404	C++
 	_harfbuzz.cp311-win_amd64.pyd!hb_subset_repack_or_fail(unsigned int table_tag, hb_object_t * hb_objects, unsigned int num_hb_objs) Line 53	C++
 	_harfbuzz.cp311-win_amd64.pyd!__pyx_pf_9uharfbuzz_9_harfbuzz_16repack_with_tag(_object * __pyx_v_tag, _object * __pyx_v_subtables, _object * __pyx_v_graphnodes, _object *) Line 29889	C++
 	_harfbuzz.cp311-win_amd64.pyd!__pyx_pw_9uharfbuzz_9_harfbuzz_17repack_with_tag(_object * __pyx_self, _object * const * __pyx_args, __int64 __pyx_nargs, _object * __pyx_kwds) Line 29508	C++
```

**Comment by behdad** [comment]
Crash doesn't happen with harfbuzz main. So maybe we just attribute it to miscompilation and roll and move on.

**Comment by behdad** [comment]
It doesn't crash with the windows-2019 (MSVC 2019) either.

**Comment by behdad** [comment]
Going to downgrade to windows-2019 for now. https://github.com/harfbuzz/uharfbuzz/pull/172
