### ISSUE TITLE
New release to pick up bugfix

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/uharfbuzz#176]
Can a new release get made which includes: https://github.com/harfbuzz/harfbuzz/pull/4385

This fixes a cases where repacking is failing (see: https://github.com/fonttools/fonttools/issues/3260).

**Comment by behdad** [comment]
I rolled HB forward in uharfbuzz. Needs a release to be made.

**Comment by anthrotype** [comment]
usually we roll forward to a tagged harfbuzz release, so it's easier to identify the version of the embedded libharfbuzz. Can you make one quick?

**Comment by anthrotype** [comment]
I can then take care of the uharfbuzz release itself

**Comment by anthrotype** [comment]
looks like our CI is already building wheels for python 3.12, so we only need to tag a new uharfbuzz release in order to publish those.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/8.2.0

**Comment by anthrotype** [comment]
thanks Khaled. I rolled forward the submodule and pushed a new tag https://github.com/harfbuzz/uharfbuzz/tree/v0.37.3, uharfbuzz wheels will be uploaded soon
