### ISSUE TITLE
Move to harfbuzz organization?

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#18]
@adrientetar would you be ok to move uharfbuzz repo under the harfbuzz github organisation?

/cc @behdad

**Comment by adrientetar** [comment]
Will I still have push access?

**Comment by anthrotype** [comment]
I don't see why not

**Comment by behdad** [comment]
@adrientetar I'll give you push to main hb repo as well, if you need!

**Comment by adrientetar** [comment]
I need permission to create repository on harfbuzz.

**Comment by behdad** [comment]
You should receive an invite to the org.

**Comment by adrientetar** [comment]
Okay, give me push access plz.

**Comment by behdad** [comment]
It says you can create new repo.  Doesn't allow transfer?

**Comment by behdad** [comment]
Or push to harfbuzz repo you mean?

**Comment by adrientetar** [comment]
I did transfer but I lost rights to the repository. I can't this issue for instance.

**Comment by behdad** [comment]
Huh!  Okay lemme fix.

**Comment by behdad** [comment]
Done.

**Comment by behdad** [comment]
And thanks!

We should add a note to https://github.com/harfbuzz/harfbuzz/blob/master/README.python.md

**Comment by adrientetar** [comment]
yea!
