### ISSUE TITLE
v0.39.2 release hiccups

### ISSUE THREAD

**Issue by alerque** [harfbuzz/uharfbuzz#199]
A couple observations on the v0.39.2 release process:

* It looks like there is a CI job that is supposed to turn the tag into a release, but it failed because the release already existed. Perhaps the GH web interface was used manually to create the release while the job was still running?
* Whether a consequence of the release CI runs not finishing on not, the [PyPi releases](https://pypi.org/project/uharfbuzz/#files) don't reflect the current version yet.

**Comment by khaledhosny** [comment]
I tagged a new release, hopefully this will fix it.

**Comment by alerque** [comment]
Yup, that appears to have worked. Other than some egregious TUI terminal stuff being sent to a non-interactive CI log and spamming it with color and location codes, the automatic deploy worked fine. I guess the mistake was just manually pushing the GH "create release" button rather than waiting for the CI workflow to do it. No big deal, thanks for the patch version bump.
