### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/uharfbuzz#206]
We don’t seem to have documentation anywhere, but we should. Even though we try to remain close to HarfBuzz C-API as much as possible, it is still non 1:1 and I often find myself looking into the source code to find the right API to use.

I don’t know what options we have for documenting Cython code, so opening this in case someone have an idea.

**Comment by madig** [comment]
I think Sphinx should be able to deal with Cython stuff as well. https://stackoverflow.com/questions/10057476/how-do-i-use-sphinx-with-cython says you may need to build the extension in place so that Sphinx can load and inspect it.
