### ISSUE TITLE
Support variable ttfs without HVAR

### ISSUE THREAD

**Issue by stenson** [harfbuzz/uharfbuzz#21]
I brought this topic up on the Font Tools & Tech discord and was instructed to file an issue here for support of TrueType-flavored VFs built without the optional HVAR table. The original issue was described here: https://github.com/harfbuzz/uharfbuzz/issues/19, though HVAR is not mentioned specifically in the issue title.

I believe the issue could be solved by using the hb_ft series of functions instead of the hb_ot series (which I've attempted in a fork of uharfbuzz, but had no success)

**Comment by behdad** [comment]
A tool to add `HVAR` table to an existing font is a good tool to have in FontTools.

A way to make uharfbuzz use hb-ft is also good to have.

**Comment by behdad** [comment]
> A tool to add `HVAR` table to an existing font is a good tool to have in FontTools.

We cannot handle hinting, but `gvar` variations should be doable.

**Comment by ebraminio** [comment]
HarfBuzz callback now support calculating extents for font without `HVAR` (from the var glyphs themselves) so this can be closed I believe.

About hb-ft part, we should either take control of freetype compile also which is unlikely, or rely on #45 for hb-ft for ones for whom need it. After compiling freetype and adding the library to `include_dirs`/`libraries`, only FT_FREETYPE_H should be passed while `pyx` compile so `hb_ft_font_set_funcs` can be accessed then be called to hb_font_t equivalent object. Guess doesn't worth the hassle.

**Comment by justvanrossum** [comment]
Confirmed that VF without HVAR now works correctly.

**Comment by behdad** [comment]
> HarfBuzz callback now support calculating extents for font without `HVAR` (from the var glyphs themselves) (IIUC?) so this can be closed I believe

Can you remind me where this was done?  I want to review. My concern is that our glyph loading is super slow currently. We might want to add a cache. The change you note exposes our extreme slowness right now. Which I'm not saying we should back down, but like to assess and plan how to fix the performance issue. Related: https://github.com/harfbuzz/harfbuzz/issues/1389

**Comment by ebraminio** [comment]
> Can you remind me where this was done? I want to review. My concern is that our glyph loading is super slow currently. We might want to add a cache. The change you note exposes our extreme slowness right now. 

When CFF/CFF2 was implemented I guess, https://github.com/harfbuzz/harfbuzz/pull/1113 maybe https://github.com/harfbuzz/harfbuzz/pull/1113/commits/c0c85b852d37dad75eeef473e6dd3ec91a3b559b

**Comment by ebraminio** [comment]
And oh the gvar part, https://github.com/harfbuzz/harfbuzz/commit/b9ff43c162e8f61cff8e48d3dcbf7c1fe263d625 which guess no different from CFF/CFF2 part.

**Comment by ebraminio** [comment]
> [..] We might want to add a cache.

Guess should be bench-marked first https://github.com/harfbuzz/harfbuzz/pull/2457 :)
