### ISSUE TITLE
`font.draw_glyph` doesn't support glyphs with a ton of points

### ISSUE THREAD

**Issue by stenson** [harfbuzz/uharfbuzz#220]
I've been experimenting with some fonts with a ton of points in each glyph (~3000) that uharfbuzz doesn't seem to be able to render completely. Obviously these are silly fonts/glyphs (just for my own personal use), but CoreText and FreeType seem to have no issue displaying the full count of points. uharfbuzz (via both FontGoggles and an experimental version of my own library coldtype) both render as below, where the count of points returned from `draw_glyph` never goes above ~2500 (though there doesn’t seem to be any kind of exact numeric limit).

I'm wondering if either uharfbuzz or harfbuzz itself has a hardcoded limit for the number of moves that can be returned to the DrawFuncs?

A macOS Finder preview above (presumably CoreText?), latest FontGoggles below with harfbuzz outlines:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/19930374-7237-4638-a7ea-6cba7b2429ab">

FontGoggles 1.5.0 rendering (with FreeType, before the switch to harfbuzz for outlines)
<img width="516" alt="image" src="https://github.com/user-attachments/assets/a08f8ccc-dd0a-4e5c-a173-619c56e9c8e3">

**Comment by justvanrossum** [comment]
Is your uharfbuzz/FontGoggles up to date? In the latest harfbuzz (and therefore uharfbuzz and FontGoggles) some limits for CFF charstrings were stretched, which could perhaps solve an issue like this.

**Comment by justvanrossum** [comment]
(Hmmm, you mention latest FontGoggles, so it may be something else.)

**Comment by justvanrossum** [comment]
Can you share this font, or maybe a subset of one glyph?

**Comment by stenson** [comment]
Ah my apologies! 1.8.3 fixes the issue completely — thanks! Thought I was up to date, my bad. Here’s a four-letter version of the font in question if you're still interested in testing it out, but I'll close this issue for now.

[NickelMagnetic_Regular_a1.otf.zip](https://github.com/user-attachments/files/17882439/NickelMagnetic_Regular_a1.otf.zip)

**Comment by behdad** [comment]
Unfortunately we have some arbitrary limits in HarfBuzz. We keep hitting them every now and then. I'll think about some alternative model, but I'm not sure how.
