### ISSUE TITLE
custom glyph_h_advance_func + nominal_glyph_func causes problem with combining marks

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#23]
I'm trying to use uharfbuzz with a custom advance width function.

The first thing I noticed that if you use `set_glyph_h_advance_func()` you _also_ have to use `set_nominal_glyph_func()`, which is a little inconvenient and unexpected, but not too hard to work around. So I also made a custom "nominal_glyph_func" function, that looks up a code point in the cmap as given by `fontTools`.

This works mostly alright.

The test font (included in the zip) contains a couple of precombined diacritics, and a mark feature that takes care of A + macroncmb and E + macroncmb. Without the custom functions, both precomposed and base + combining mark work as text input. But as soon as I use the custom functions neither work anymore. See the `showProblem` switch in the test script.

It may very well that I'm not using the API correctly, but if so, I don't have a clue what I'm doing wrong.

[testdata+script.zip](https://github.com/harfbuzz/uharfbuzz/files/4087466/testdata%2Bscript.zip)

**Comment by khaledhosny** [comment]
I think it is a bug in how uharfbuzz handles `get_nominal_glyph`; HarfBuzz expects the function to return false when the character is not supported by the font, but `uhharfbuzz` returns true unconditionally:
https://github.com/harfbuzz/uharfbuzz/blob/7638ed0dd0401907fa92729689c7188d5d4e0d69/src/uharfbuzz/_harfbuzz.pyx#L377-L384

**Comment by khaledhosny** [comment]
(I think it wasn’t a good idea to hide this from the Python API users, the callback should have been made to return both glyph id and a boolean to give the callers full control).

**Comment by justvanrossum** [comment]
Wow, thanks Khaled! That's indeed the problem. My fix makes sense to me (.notdef is not def after all), and I hope it is indeed correct.

**Comment by khaledhosny** [comment]
This should work for callbacks returning 0 for unsupported character (the most common case), however it should be possible to return a non-0 glyph id and still mark it as unsupported character, though that might be not be worth the trouble at this point.
