### ISSUE TITLE
switch to meson build system

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#29]
upstream [Harfbuzz library will be switching to use meson](https://github.com/harfbuzz/harfbuzz/issues?q=is%3Aissue+is%3Aopen+label%3Ameson) as its build system, which means they may drop support for CMake some time in the future.
For uharfbuzz bindings, we use scikit-build as our python build system, which in turn uses CMake to orchestrate the build.
We should see if we can use Meson to build the cython extension module instead of CMake.

There's a package called [mesonpep517](https://gitlab.com/thiblahute/mesonpep517) that helps with creating python dists and wheels with meson (see [mesonpep517 docs](https://thiblahute.gitlab.io/mesonpep517/))

On mesonbuild repo there's an example of a cython module built with meson:
https://github.com/mesonbuild/meson/tree/master/test%20cases/python3/3%20cython

**Comment by khaledhosny** [comment]
I think we should be able build the `src/harfbuzz.cc` file from HarfBuzz directly with setuptools and skip HarfBuzz build system altogether. Something like what we do in psautohint, since we don’t really need to detect any dependencies and all HarfBuzz optional features can be controlled with compiler definitions.

**Comment by anthrotype** [comment]
> build the src/harfbuzz.cc file from HarfBuzz directly with setuptools and skip HarfBuzz build system

Yes, if we could do that, that'd be good.

> optional features can be controlled with compiler definitions

are those documented somewhere?

**Comment by anthrotype** [comment]
you probably mean the HAVE_X, HAVE_Y, etc. sorts of preprocessor definitions that are controlled via harfbuzz's ./configure script.

I must say that the cmake-based setup that we currently have in uharfbuzz is quite neat though. I like that one pip install cmake and ninja and have cmake download tarball, verify, configure, install, compile, link, etc. But sure, I'm all for simplifying that if we can.

**Comment by khaledhosny** [comment]
These are for external dependencies, but I was talking about https://github.com/harfbuzz/harfbuzz/blob/master/CONFIG.md#pre-defined-configurations

**Comment by anthrotype** [comment]
Thank you Ebrahim?

**Comment by justvanrossum** [comment]
I'm trying to build locally and am getting an error:

```
    src/uharfbuzz/_harfbuzz.cpp:646:10: fatal error: 'hb.h' file not found
```

What could be wrong on my end?

Full output:

```
(uharfbuzz-upstream) JvR:uharfbuzz just$ pip install -e .
Obtaining file:///Users/just/code/git/uharfbuzz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: uharfbuzz
  Attempting uninstall: uharfbuzz
    Found existing installation: uharfbuzz 0.12.1.dev1+g985eda0
    Uninstalling uharfbuzz-0.12.1.dev1+g985eda0:
      Successfully uninstalled uharfbuzz-0.12.1.dev1+g985eda0
  Running setup.py develop for uharfbuzz
    ERROR: Command errored out with exit status 1:
     command: /Users/just/code/git/uharfbuzz/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/just/code/git/uharfbuzz/setup.py'"'"'; __file__='"'"'/Users/just/code/git/uharfbuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/just/code/git/uharfbuzz/
    Complete output (14 lines):
    running develop
    running egg_info
    writing src/uharfbuzz.egg-info/PKG-INFO
    writing dependency_links to src/uharfbuzz.egg-info/dependency_links.txt
    writing top-level names to src/uharfbuzz.egg-info/top_level.txt
    writing manifest file 'src/uharfbuzz.egg-info/SOURCES.txt'
    running build_ext
    building 'uharfbuzz._harfbuzz' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DHB_NO_MT=1 -Iharfbuzz/src -I/Users/just/code/git/uharfbuzz/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/uharfbuzz/_harfbuzz.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/uharfbuzz/_harfbuzz.o -std=c++11
    src/uharfbuzz/_harfbuzz.cpp:646:10: fatal error: 'hb.h' file not found
    #include "hb.h"
             ^~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of uharfbuzz
  Moving to /Users/just/code/git/uharfbuzz/venv/lib/python3.7/site-packages/uharfbuzz.egg-link
   from /private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-uninstall-luyvo692/uharfbuzz.egg-link
ERROR: Command errored out with exit status 1: /Users/just/code/git/uharfbuzz/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/just/code/git/uharfbuzz/setup.py'"'"'; __file__='"'"'/Users/just/code/git/uharfbuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by justvanrossum** [comment]
(I should perhaps have commented on the PR or have opened a new issue, sorry!)

**Comment by anthrotype** [comment]
Have you initialised the git submodules?

git submodules update --init

**Comment by anthrotype** [comment]
We should mention in readme that one should git clone --recursive, or alternatively git submodule update --init afterwards

**Comment by justvanrossum** [comment]
That did it, thanks!
