### ISSUE TITLE
autogenerate pxd from harfbuzz headers

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#3]
I've been experimenting with:
https://github.com/tarruda/python-autopxd

besides a few py3 glitches it seems to work quite well.

I only had to add a `from libc.stdint cimport *` for the fixed-with integer types and a few "opaque" ctypedef struct definitions.
I think we could fix these, and then we would be able to simply run this autopxd script to autogenerate the pxd cython declarations from the harfbuzz hb.h (and hb-ot.h) headers.

**Comment by ebraminio** [comment]
that py3 glitches unfortunately, perhaps py2 support can be completely deleted there.

**Comment by khaledhosny** [comment]
This repository does not to have been updated in 4 years, and I’d not like to have a dependency on an abandoned project. Copying declarations manually is bit tedious, but HarfBuzz APIs is stable so it has to be done once for any given symbol.
