### ISSUE TITLE
Not all features reported by ot_layout_language_get_feature_tags() due to 24 max

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#31]
https://github.com/harfbuzz/uharfbuzz/blob/e9b86bdfd819e3e7d2d7e67682e2294a159a26ae/src/uharfbuzz/_harfbuzz.pyx#L524

Also `ot_layout_script_get_language_tags()`:
https://github.com/harfbuzz/uharfbuzz/blob/e9b86bdfd819e3e7d2d7e67682e2294a159a26ae/src/uharfbuzz/_harfbuzz.pyx#L545

And `ot_layout_table_get_script_tags()`:
https://github.com/harfbuzz/uharfbuzz/blob/e9b86bdfd819e3e7d2d7e67682e2294a159a26ae/src/uharfbuzz/_harfbuzz.pyx#L563

This is the root cause of justvanrossum/fontgoggles#63

Funny thing: I just noticed this limitation in uharfbuzz a couple of days ago and wondered when we'd see a real-world report, and here we are :)

I'll try to write a fix.

**Comment by khaledhosny** [comment]
If `malloc`ing is not desired, you keep looping untill there are no more items to get. Here is an example https://github.com/ufyTeX/luaharfbuzz/blob/master/src/luaharfbuzz/face.c#L98-L119

**Comment by justvanrossum** [comment]
Thanks, that's exactly the approach I had in mind.

**Comment by justvanrossum** [comment]
Fixed in release 1.1.6.
