### ISSUE TITLE
Add GlyphInfo.name?

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#36]
I think a nice addition would be to have a `GlyphInfo.name` or `GlyphInfo.glyph_name` attribute.

To get the glyph name, I currently need to use fonttools to extract the glyph order from the font.

Btw. what would be the HB call to get a glyph name from a glyph ID?

**Comment by khaledhosny** [comment]
[`ـhb_font_get_glyph_nameـ()`](https://harfbuzz.github.io/harfbuzz-hb-font.html#hb-font-get-glyph-name)

**Comment by justvanrossum** [comment]
Thanks, I'll make a PR soon-ish.

**Comment by justvanrossum** [comment]
Ah, an `info.name` attribute is not possible as the GlyphInfo object has no reference to the font object. Perhaps it needs to be a font method: `font.get_glyph_name(gid)`.

**Comment by justvanrossum** [comment]
The other thing is that I'm a bit spoiled with how fonttools synthesizes glyph names when there aren't any in the font, such as for a TTF with a `post` format 3.0 table. `hb_font_get_glyph_name()` rightfully does not succeed in those cases.

**Comment by khaledhosny** [comment]
Yes it is rather low level. I suggest we keep the `uharfbuzz` binding straight forward, and let client code do fallback of needed, or added fallback but make it optional.

**Comment by justvanrossum** [comment]
What do you think is better: return None on failure to get a glyph name, or raise ValueError? I'm inclined to return None, as that's easier to handle.

**Comment by khaledhosny** [comment]
Yes, I think None is better (I’m not a big fan of raising for non error cases, and missing a glyph name is not an error).

**Comment by behdad** [comment]
`hb_font_glyph_to_string` does produce `gidXYZ` if glyph has no name.

**Comment by justvanrossum** [comment]
Ah, then `hb_font_glyph_to_string()` should be added as `font.glyph_to_string()`.

**Comment by roberto-arista** [comment]
Hey!
Can I suggest to add `font.glyph_to_string()` method to the example in the readme?

Took me a while to dig into all the closed issues to find a possible answer to my question. I believe getting glyph names might be a common use case.

**Comment by anthrotype** [comment]
@roberto-arista sounds good, would you like to PR that?
