### ISSUE TITLE
Option to link against installed harfbuzz

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/uharfbuzz#45]
My harfbuzz is often not like your harfbuzz, so downloading and building a vendor harfbuzz isn't something I want uharfbuzz to do. Obviously it's a good idea for platforms where you can't be sure harfbuzz is installed already, but it's unnecessary in many cases when you can just link against the system version. Can we make that an option?

**Comment by anthrotype** [comment]
yes, we should add an option. Given we should soon switch away from cmake build system (see #29) it should be done as part of that effort.

**Comment by ebraminio** [comment]
> yes, we should add an option. Given we should soon switch away from cmake build system (see #29) it should be done as part of that effort.

#49

**Comment by BwL1289** [comment]
@anthrotype has there been any update on this? it doesn't look like the meson build system was ever adopted.

we need to link against our system harfbuzz to avoid breaking abi compatibility.

**Comment by khaledhosny** [comment]
We currently use some experimental HarfBuzz APIs that are unlikely to be enabled in system HarfBuzz (because they are not stable APIs and HarfBuzz build does not enable them by default), so even if other technical issues get addressed, it might still not be possible to link to system HarfBuzz for most users.

**Comment by BwL1289** [comment]
@khaledhosny thanks for the response. That will break ABI compatibility with a number of other libraries for us unfortunately.

Can you specify which experimental harfbuzz APIs are enabled in the vendored version?

**Comment by khaledhosny** [comment]
We use `hb_subset_repack_or_fail()`.

**Comment by BwL1289** [comment]
Thanks. We enable experimental APIs in our system harfbuzz so I might be able to fork as a last resort.

Would love to see an official option for this if possible.

**Comment by khaledhosny** [comment]
PRs are always welcome.

**Comment by BwL1289** [comment]
@khaledhosny our build is working on all platforms for CPython and fully working on windows but failing for PyPy for macos and ubuntu starting with PyPy 3.8. 

Are you able to help with getting PyPy to work? We are not familiar with it.
