### ISSUE TITLE
message callback API should respect return value

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#51]
https://twitter.com/simoncozens/status/1275806808104370176

We currently always return 1:
https://github.com/harfbuzz/uharfbuzz/blob/0a584e6aa7dad90b229a20e4daaaa4a4b153c379/src/uharfbuzz/_harfbuzz.pyx#L25-L27

**Comment by khaledhosny** [comment]
I think we need to also pass the buffer and the font to the callback function, I have no idea why this was not done before but it seems to seriously affect its usefulness. This would be a breaking change, though.

**Comment by justvanrossum** [comment]
> I think we need to also pass the buffer and the font to the callback function, I have no idea why this was not done before but it seems to seriously affect its usefulness.

Don't know why it was done this way, but using a method, a nested function, or functools.partial I don't think there's anything we can't do currently.

**Comment by khaledhosny** [comment]
OK, lets leave it as it is for now (I think we can handle the extra arguments in a backward-compatible way, but lets worry about this when we have to).
