### ISSUE TITLE
Readme example: `hb.ot_font_set_funcs(font)` needed?

### ISSUE THREAD

**Issue by madig** [harfbuzz/uharfbuzz#66]
https://harfbuzz.github.io/harfbuzz-hb-ot-font.html#hb-ot-font-set-funcs says it's already called on `hb_font_create`, which `uharfbuzz.Font` does. Does it need to be there?

**Comment by justvanrossum** [comment]
I think you're right and that it's indeed redundant. Care to make a PR?
