### ISSUE TITLE
Random thought: set `scale` automatically in `hb.Font.__cinit__`?

### ISSUE THREAD

**Issue by madig** [harfbuzz/uharfbuzz#68]
Is there a reason to require the user to set it explicitly afterwards? Would shave another two lines off the example.

**Comment by justvanrossum** [comment]
If I remove the corresponding lines from the tests, they still pass... Perhaps it's already set to upem by default?

**Comment by madig** [comment]
Yup: https://github.com/harfbuzz/harfbuzz/blob/2.7.4/src/hb-font.cc#L1506

PR incoming.
