### ISSUE TITLE
link with freetype and add support for hb_ft_* functions

### ISSUE THREAD

**Issue by ralsina** [harfbuzz/uharfbuzz#7]
Using a different binding I had a line like this:

```
face.set_char_size(size=1, resolution=64)
```

I can't find the equivalent in uharfbuzz (or in harfbuzz for that matter ;-)

Any ideas?

**Comment by anthrotype** [comment]
sorry, that's freetype, not harfbuzz
https://gitlab.com/ldo/python_freetype/blob/master/freetype2.py#L2074

**Comment by ralsina** [comment]
Then in what unit is harfbuzz calculating offsets?

**Comment by anthrotype** [comment]
in the README's example, we set the font's X and Y scale to the UPEM, so the values are in abstract font units, i.e. not scaled.
The harfbuzz library that's statically linked in the uharfbuzz extension module currently doesn't also include freetype -- neither it links dynamically to the system freetype --, thus all the functions in `hb-ft.h` header are currently not available here.

**Comment by anthrotype** [comment]
i'll keep the issue open for when we'll find the time to deal with this. I am busy with other things, and also to be honest I'm not very familiar with the harfbuzz API itself (i'm sure you know more than me).
Sorry if I could not help you more.

**Comment by HinTak** [comment]
Shameless plug https://github.com/HinTak/harfbuzz-python-demos

**Comment by khaledhosny** [comment]
It is not clear to me what `hb_ft_*` are needed for here.

**Comment by ralsina** [comment]
Unsubscribing, not interested in uharfbuzz anymore.

**Comment by justvanrossum** [comment]
I think we should close this. No need for ft at all, esp. since freetype-py can cooperate nicely with uharfbuzz.

**Comment by khaledhosny** [comment]
I agree.
