### ISSUE TITLE
running tests on pypy3 fails

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#74]
I noticed this while setting up Github Actions #73, since cibuildwheel attempts to build a wheel for pypy by default.
These are the failues:
https://github.com/harfbuzz/uharfbuzz/runs/1919782201?check_suite_focus=true#step:6:1008
https://ci.appveyor.com/project/fonttools/uharfbuzz/builds/37821221

**Comment by khaledhosny** [comment]
Looks like a bug in handling non-ASCII characters. Something is not working right in `Buffer.add_str()`. Probably https://foss.heptapod.net/pypy/pypy/-/issues/3413.
