### ISSUE TITLE
how to get reshaped unicodes instead of codepoints 

### ISSUE THREAD

**Issue by ahmed4end** [harfbuzz/uharfbuzz#75]
i jus used the example provided in the repo but the result was just unexpected i used to expect unicode string that i can work with it now it's just something like this "gid968=1@943,0+0" which is not very workable or provided with insights, so is there a way to get reshaped unicode as output ? or how to convert this "gid968" to unicode !

**Comment by simoncozens** [comment]
One of the first things a shaping engine will do is map Unicode code points to glyph IDs in the font. What are you trying to do? What do you mean by “reshaped Unicodes”?

**Comment by HinTak** [comment]
The glyph id to unicode mapping is provided by the font's cmap table, and many font accessing tool/api let you do that. It is also font-specific. The shaping engine (such as and including harfbuzz) provides you with a unicode to glyph id + offset / positioning (those numbers after @) mapping. If you want to do the reverse, here would be a wrong place...
