### ISSUE TITLE
[Not an issue] i need an advice.

### ISSUE THREAD

**Issue by ahmed4end** [harfbuzz/uharfbuzz#76]
I'm sorry for asking this here, can you recommend me a book or reference or article or any resource about Arabic fonts unicode reshaping that i can learn from it how the Arabic text are reshaped so i can implement it in code ?

**Comment by chrissimpkins** [comment]
Maybe this would be helpful? 

https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-arabic.md

**Comment by behdad** [comment]
I don't know of a book. But this is simple enough to study: https://github.com/fribidi/pyarabicshaping

**Comment by ahmed4end** [comment]
@chrissimpkins thanks very much
