### ISSUE TITLE
enable uniscribe fallback shaper when building on windows

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#77]
Since we did it for CoreText on macOS, would be good to also do it for the native shaper on Windows.
I'm not sure how difficult that would be, any help appreciated.

BTW, I recently discovered that @paullinnerud at Microsoft have been working on a uharfbuzz-like cython module that wraps DirectWrite API with an interface almost identical to uharfbuzz, check it out at https://github.com/microsoft/DWriteShapePy

**Comment by simoncozens** [comment]
Interesting. I have been planning to wrap uharfbuzz/Uniscribe in an Azure Function. This would probably make it a lot easier.

**Comment by behdad** [comment]
This should be a one-liner no matter how you build HB.

**Comment by behdad** [comment]
> ...with an interface almost identical to uharfbuzz, check it out at https://github.com/microsoft/DWriteShapePy

lol. The copied example even still says `hb` instead of `dw` in one place:
```

face = hb.Face(fontdata)
font = dw.Font(face)
upm = font.upem
print(upm)
```

**Comment by khaledhosny** [comment]
HarfBuzz also have a DirectWrite shaper, if someone wants to fix it...
