### ISSUE TITLE
coretext shaper causes segfault on "sparse" font

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#83]
I have a font that only has GPOS, cmap, head, maxp and post tables, which works perfectly fine for the default (ot) shaper, but crashes hard when specifying the coretext shaper on macOS.

Relates to https://github.com/justvanrossum/fontgoggles/pull/144

(FontGoggles compiles this kind of minimal fonts on the fly to do shaping for UFO sources: metrics come from the source via hb callbacks, and outlines are directly drawn from the sources, too.)

I'll open a PR that reproduces the problem.

**Comment by behdad** [comment]
> (FontGoggles compiles this kind of minimal fonts on the fly to do shaping for UFO sources: metrics come from the source via hb callbacks, and outlines are directly drawn from the sources, too.)

Beautiful. I had designed HB to be used that way :).

Does the crash reproduce with hb-view?

**Comment by justvanrossum** [comment]
> Beautiful. I had designed HB to be used that way :).

It's pretty fantastic indeed :)

> Does the crash reproduce with hb-view?

It fails gracefully like this:
```
$ hb-view testfont.ttf ABC --shapers=coretext
hb-view: all shapers failed.
hb-view: FT_New_Memory_Face fail
```
So no, it doesn't crash.
