### ISSUE TITLE
support building arm64 wheels for Apple Silicon architecture

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/uharfbuzz#85]
in addition to the `x86_64` wheels that we already build, cibuildwheel project can now also build native wheels for the Apple Silicon platform, see https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon on how to enable those

**Comment by khaledhosny** [comment]
Should we build `arm64` or `universal2`, @justvanrossum would `universal2` wheel help with FontGoggles binary distribution?

**Comment by anthrotype** [comment]
Most other projects (e.g. numpy) build both

**Comment by justvanrossum** [comment]
TBH I still have zero experience with Silicon, but looking at what other projects do sounds like a good idea.

**Comment by khaledhosny** [comment]
OK, lets do both then.
