### ISSUE TITLE
No win_amd64 wheels were produced for last release (0.16.0)

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/uharfbuzz#86]
https://pypi.org/project/uharfbuzz/0.16.0/#files

**Comment by anthrotype** [comment]
we run cibuildwheel to build both the win32 adn amd64 wheel one after the other in the same windows instance. Something is leaving behind the repository in dirty state because by the time the 64-bit wheel gets built, setuptools_scm sees untracked files and assigns the new wheel a local version which can't be uplaoded to PyPI

https://ci.appveyor.com/project/fonttools/uharfbuzz/builds/39074250#L1916

**Comment by anthrotype** [comment]
it's strange because it was working fine untile the penultimate release

**Comment by anthrotype** [comment]
oh! I see what's going on.. After running `pytest`, I see the `harfbuzz` git submodule contains untracked content, it's  `test/subset/__pycache__`. The fix should be to add that to upstream harfbuzz .gitignore. But why does that get imported in our tests?

**Comment by justvanrossum** [comment]
The other strange thing is that I didn't get any AppVeyor fail notification after I tagged a release. Is that to be expected, with the way AppVeyor is set up?

(I only accidentally discovered there were no 64 bit wheels because I saw another CI process suspiciously build uharfbuzz wheels...)

**Comment by anthrotype** [comment]
I just set it up to email fonttools-dev@googlegroups.com when build fails or build status change

**Comment by anthrotype** [comment]
the appveyor bot is under the fonttools organization, should we spam harfbuzz instead? It doesn't really matter

**Comment by justvanrossum** [comment]
I don't really know. Longer-term I'd prefer to move away from AppVeyor and have #87 working instead.

**Comment by anthrotype** [comment]
if you like i can invite you as collaborator to the appveyor fonttools account so you should get email notifications (need an email address to send to)

**Comment by justvanrossum** [comment]
Sure, my GH username @ gmail is good.

**Comment by anthrotype** [comment]
> Longer-term I'd prefer to move away from AppVeyor and have #87 working instead.

true, but until it works and is free, reliable and fast I don't see an urgent reason to switch. The github windows runners have given me headaches sometimes (e.g. the temporary directory is a different drive than the one where the code was cloned to and os.path.relpath errors out when across mount points)

**Comment by justvanrossum** [comment]
> github windows runners have given me headaches sometimes

Right, and this is another such headache...
